<?php
/**
 * Core functions for WP Bottom Navigation Pro
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Get plugin settings
 */
function wpbnp_get_settings() {
    $defaults = wpbnp_get_default_settings();
    $settings = get_option('wpbnp_settings', $defaults);
    
    return wp_parse_args($settings, $defaults);
}

/**
 * Get default settings
 */
function wpbnp_get_default_settings() {
    return apply_filters('wpbnp_default_settings', array(
        'enabled' => true,
        'preset' => 'minimal',
        'items' => array(
            array(
                'id' => 'home',
                'icon' => 'dashicons-admin-home',
                'label' => __('Home', 'wp-bottom-navigation-pro'),
                'url' => home_url(),
                'enabled' => true,
                'roles' => array(),
                'badge_count' => 0
            ),
            array(
                'id' => 'shop',
                'icon' => 'dashicons-cart',
                'label' => __('Shop', 'wp-bottom-navigation-pro'),
                'url' => '#',
                'enabled' => true,
                'roles' => array(),
                'badge_count' => 0
            ),
            array(
                'id' => 'account',
                'icon' => 'dashicons-admin-users',
                'label' => __('Account', 'wp-bottom-navigation-pro'),
                'url' => '#',
                'enabled' => true,
                'roles' => array(),
                'badge_count' => 0
            )
        ),
        'style' => array(
            'background_color' => '#ffffff',
            'text_color' => '#666666',
            'active_color' => '#0073aa',
            'hover_color' => '#0085ba',
            'icon_color' => '#666666',
            'border_color' => '#e0e0e0',
            'height' => '60',
            'border_radius' => '0',
            'box_shadow' => '0 -2px 8px rgba(0,0,0,0.1)',
            'font_size' => '12',
            'font_weight' => '400',
            'icon_size' => '20',
            'padding' => '10'
        ),
        'animations' => array(
            'enabled' => true,
            'type' => 'bounce',
            'duration' => '300'
        ),
        'devices' => array(
            'mobile' => array(
                'enabled' => true,
                'breakpoint' => '768'
            ),
            'tablet' => array(
                'enabled' => true,
                'breakpoint' => '1024'
            ),
            'desktop' => array(
                'enabled' => false,
                'breakpoint' => '1025'
            )
        ),
        'display_rules' => array(
            'user_roles' => array(),
            'pages' => array(),
            'hide_on_admin' => true
        ),
        'badges' => array(
            'enabled' => true,
            'background_color' => '#ff4444',
            'text_color' => '#ffffff',
            'border_radius' => '50'
        ),
        'advanced' => array(
            'z_index' => '9999',
            'fixed_position' => 'bottom',
            'custom_css' => ''
        )
    ));
}

/**
 * Sanitize plugin settings
 */
function wpbnp_sanitize_settings($settings) {
    $sanitized = array();
    
    // Boolean values
    $sanitized['enabled'] = !empty($settings['enabled']);
    
    // String values
    $sanitized['preset'] = sanitize_text_field($settings['preset'] ?? 'minimal');
    
    // Items array
    if (isset($settings['items']) && is_array($settings['items'])) {
        $sanitized['items'] = array();
        foreach ($settings['items'] as $item) {
            $sanitized_item = array(
                'id' => sanitize_key($item['id'] ?? ''),
                'icon' => sanitize_text_field($item['icon'] ?? ''),
                'label' => sanitize_text_field($item['label'] ?? ''),
                'url' => esc_url_raw($item['url'] ?? ''),
                'enabled' => !empty($item['enabled']),
                'roles' => array_map('sanitize_text_field', (array) ($item['roles'] ?? array())),
                'badge_count' => absint($item['badge_count'] ?? 0)
            );
            $sanitized['items'][] = $sanitized_item;
        }
    }
    
    // Style settings
    if (isset($settings['style']) && is_array($settings['style'])) {
        $sanitized['style'] = array(
            'background_color' => sanitize_hex_color($settings['style']['background_color'] ?? '#ffffff'),
            'text_color' => sanitize_hex_color($settings['style']['text_color'] ?? '#666666'),
            'active_color' => sanitize_hex_color($settings['style']['active_color'] ?? '#0073aa'),
            'hover_color' => sanitize_hex_color($settings['style']['hover_color'] ?? '#0085ba'),
            'icon_color' => sanitize_hex_color($settings['style']['icon_color'] ?? '#666666'),
            'border_color' => sanitize_hex_color($settings['style']['border_color'] ?? '#e0e0e0'),
            'height' => absint($settings['style']['height'] ?? 60),
            'border_radius' => absint($settings['style']['border_radius'] ?? 0),
            'box_shadow' => sanitize_text_field($settings['style']['box_shadow'] ?? '0 -2px 8px rgba(0,0,0,0.1)'),
            'font_size' => absint($settings['style']['font_size'] ?? 12),
            'font_weight' => sanitize_text_field($settings['style']['font_weight'] ?? '400'),
            'icon_size' => absint($settings['style']['icon_size'] ?? 20),
            'padding' => absint($settings['style']['padding'] ?? 10)
        );
    }
    
    // Animation settings
    if (isset($settings['animations']) && is_array($settings['animations'])) {
        $sanitized['animations'] = array(
            'enabled' => !empty($settings['animations']['enabled']),
            'type' => sanitize_text_field($settings['animations']['type'] ?? 'bounce'),
            'duration' => absint($settings['animations']['duration'] ?? 300)
        );
    }
    
    // Device settings
    if (isset($settings['devices']) && is_array($settings['devices'])) {
        $sanitized['devices'] = array();
        foreach (array('mobile', 'tablet', 'desktop') as $device) {
            if (isset($settings['devices'][$device])) {
                $sanitized['devices'][$device] = array(
                    'enabled' => !empty($settings['devices'][$device]['enabled']),
                    'breakpoint' => absint($settings['devices'][$device]['breakpoint'] ?? 0)
                );
            }
        }
    }
    
    // Display rules
    if (isset($settings['display_rules']) && is_array($settings['display_rules'])) {
        $sanitized['display_rules'] = array(
            'user_roles' => array_map('sanitize_text_field', (array) ($settings['display_rules']['user_roles'] ?? array())),
            'pages' => array_map('absint', (array) ($settings['display_rules']['pages'] ?? array())),
            'hide_on_admin' => !empty($settings['display_rules']['hide_on_admin'])
        );
    }
    
    // Badge settings
    if (isset($settings['badges']) && is_array($settings['badges'])) {
        $sanitized['badges'] = array(
            'enabled' => !empty($settings['badges']['enabled']),
            'background_color' => sanitize_hex_color($settings['badges']['background_color'] ?? '#ff4444'),
            'text_color' => sanitize_hex_color($settings['badges']['text_color'] ?? '#ffffff'),
            'border_radius' => absint($settings['badges']['border_radius'] ?? 50)
        );
    }
    
    // Advanced settings
    if (isset($settings['advanced']) && is_array($settings['advanced'])) {
        $sanitized['advanced'] = array(
            'z_index' => absint($settings['advanced']['z_index'] ?? 9999),
            'fixed_position' => sanitize_text_field($settings['advanced']['fixed_position'] ?? 'bottom'),
            'custom_css' => wp_strip_all_tags($settings['advanced']['custom_css'] ?? '')
        );
    }
    
    return apply_filters('wpbnp_sanitize_settings', $sanitized, $settings);
}

/**
 * Get available presets
 */
function wpbnp_get_presets() {
    $presets_file = WPBNP_PLUGIN_DIR . 'presets/default-presets.json';
    
    if (file_exists($presets_file)) {
        $presets_json = file_get_contents($presets_file);
        $presets = json_decode($presets_json, true);
        
        if (json_last_error() === JSON_ERROR_NONE) {
            return $presets;
        }
    }
    
    // Fallback presets
    return array(
        'minimal' => array(
            'name' => __('Minimal', 'wp-bottom-navigation-pro'),
            'description' => __('Clean and simple design', 'wp-bottom-navigation-pro'),
            'style' => array(
                'background_color' => '#ffffff',
                'text_color' => '#333333',
                'active_color' => '#0073aa',
                'border_color' => '#e0e0e0',
                'height' => 60,
                'border_radius' => 0,
                'box_shadow' => '0 -2px 8px rgba(0,0,0,0.1)'
            )
        ),
        'dark' => array(
            'name' => __('Dark Mode', 'wp-bottom-navigation-pro'),
            'description' => __('Dark theme for better night viewing', 'wp-bottom-navigation-pro'),
            'style' => array(
                'background_color' => '#1a1a1a',
                'text_color' => '#ffffff',
                'active_color' => '#4a9eff',
                'border_color' => '#333333',
                'height' => 60,
                'border_radius' => 0,
                'box_shadow' => '0 -2px 8px rgba(0,0,0,0.3)'
            )
        ),
        'material' => array(
            'name' => __('Material Design', 'wp-bottom-navigation-pro'),
            'description' => __('Google Material Design inspired', 'wp-bottom-navigation-pro'),
            'style' => array(
                'background_color' => '#f5f5f5',
                'text_color' => '#424242',
                'active_color' => '#2196f3',
                'border_color' => '#e0e0e0',
                'height' => 56,
                'border_radius' => 0,
                'box_shadow' => '0 -4px 8px rgba(0,0,0,0.12)'
            )
        ),
        'ios' => array(
            'name' => __('iOS Style', 'wp-bottom-navigation-pro'),
            'description' => __('Apple iOS inspired design', 'wp-bottom-navigation-pro'),
            'style' => array(
                'background_color' => '#f8f8f8',
                'text_color' => '#8e8e93',
                'active_color' => '#007aff',
                'border_color' => '#c6c6c8',
                'height' => 83,
                'border_radius' => 0,
                'box_shadow' => '0 -1px 0 rgba(0,0,0,0.1)'
            )
        )
    );
}

/**
 * Get available icon libraries
 */
function wpbnp_get_icon_libraries() {
    return array(
        'dashicons' => array(
            'name' => 'Dashicons',
            'description' => 'WordPress native icons',
            'class_prefix' => 'dashicons',
            'type' => 'font'
        ),
        'fontawesome' => array(
            'name' => 'FontAwesome',
            'description' => 'Most popular icon library',
            'class_prefix' => 'fas fa-',
            'type' => 'font',
            'cdn' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'
        ),
        'feather' => array(
            'name' => 'Feather Icons',
            'description' => 'Simple and beautiful icons',
            'class_prefix' => 'feather-',
            'type' => 'svg'
        ),
        'material' => array(
            'name' => 'Material Icons',
            'description' => 'Google Material Design',
            'class_prefix' => 'material-icons',
            'type' => 'font',
            'cdn' => 'https://fonts.googleapis.com/icon?family=Material+Icons'
        ),
        'bootstrap' => array(
            'name' => 'Bootstrap Icons',
            'description' => 'Bootstrap icon library',
            'class_prefix' => 'bi bi-',
            'type' => 'font',
            'cdn' => 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css'
        ),
        'apple' => array(
            'name' => 'Apple SF Symbols',
            'description' => 'iOS-style icons',
            'class_prefix' => 'apple-',
            'type' => 'custom'
        )
    );
}

/**
 * Get Dashicons data
 */
function wpbnp_get_dashicons() {
    return array(
        // Navigation & Home
        'dashicons-admin-home' => 'Home',
        'dashicons-admin-site' => 'Site',
        'dashicons-admin-site-alt' => 'Site Alt',
        'dashicons-admin-site-alt2' => 'Site Alt 2',
        'dashicons-admin-site-alt3' => 'Site Alt 3',
        
        // Users & People
        'dashicons-admin-users' => 'Users',
        'dashicons-admin-user' => 'User',
        'dashicons-buddicons-activity' => 'Activity',
        'dashicons-buddicons-buddypress-logo' => 'Community',
        'dashicons-buddicons-community' => 'Community Alt',
        'dashicons-buddicons-friends' => 'Friends',
        'dashicons-buddicons-groups' => 'Groups',
        'dashicons-buddicons-pm' => 'Messages',
        'dashicons-buddicons-replies' => 'Replies',
        'dashicons-buddicons-topics' => 'Topics',
        
        // Shopping & Commerce
        'dashicons-cart' => 'Cart',
        'dashicons-store' => 'Store',
        'dashicons-money' => 'Money',
        'dashicons-money-alt' => 'Money Alt',
        'dashicons-products' => 'Products',
        'dashicons-businesswoman' => 'Business',
        'dashicons-businessperson' => 'Business Person',
        
        // Content & Media
        'dashicons-admin-media' => 'Media',
        'dashicons-admin-page' => 'Page',
        'dashicons-admin-post' => 'Post',
        'dashicons-admin-comments' => 'Comments',
        'dashicons-format-image' => 'Image',
        'dashicons-format-gallery' => 'Gallery',
        'dashicons-format-video' => 'Video',
        'dashicons-format-audio' => 'Audio',
        'dashicons-format-chat' => 'Chat',
        'dashicons-camera' => 'Camera',
        'dashicons-camera-alt' => 'Camera Alt',
        'dashicons-images-alt' => 'Images',
        'dashicons-images-alt2' => 'Images Alt',
        'dashicons-video-alt' => 'Video Alt',
        'dashicons-video-alt2' => 'Video Alt 2',
        'dashicons-video-alt3' => 'Video Alt 3',
        
        // Communication
        'dashicons-email' => 'Email',
        'dashicons-email-alt' => 'Email Alt',
        'dashicons-email-alt2' => 'Email Alt 2',
        'dashicons-phone' => 'Phone',
        'dashicons-smartphone' => 'Smartphone',
        'dashicons-networking' => 'Networking',
        'dashicons-rss' => 'RSS',
        'dashicons-share' => 'Share',
        'dashicons-share-alt' => 'Share Alt',
        'dashicons-share-alt2' => 'Share Alt 2',
        
        // Navigation & Controls
        'dashicons-menu' => 'Menu',
        'dashicons-menu-alt' => 'Menu Alt',
        'dashicons-menu-alt2' => 'Menu Alt 2',
        'dashicons-menu-alt3' => 'Menu Alt 3',
        'dashicons-arrow-up' => 'Arrow Up',
        'dashicons-arrow-down' => 'Arrow Down',
        'dashicons-arrow-left' => 'Arrow Left',
        'dashicons-arrow-right' => 'Arrow Right',
        'dashicons-arrow-up-alt' => 'Arrow Up Alt',
        'dashicons-arrow-down-alt' => 'Arrow Down Alt',
        'dashicons-arrow-left-alt' => 'Arrow Left Alt',
        'dashicons-arrow-right-alt' => 'Arrow Right Alt',
        'dashicons-arrow-up-alt2' => 'Arrow Up Alt 2',
        'dashicons-arrow-down-alt2' => 'Arrow Down Alt 2',
        'dashicons-arrow-left-alt2' => 'Arrow Left Alt 2',
        'dashicons-arrow-right-alt2' => 'Arrow Right Alt 2',
        
        // Actions & Controls
        'dashicons-plus' => 'Plus',
        'dashicons-plus-alt' => 'Plus Alt',
        'dashicons-plus-alt2' => 'Plus Alt 2',
        'dashicons-minus' => 'Minus',
        'dashicons-dismiss' => 'Dismiss',
        'dashicons-yes' => 'Yes',
        'dashicons-yes-alt' => 'Yes Alt',
        'dashicons-no' => 'No',
        'dashicons-no-alt' => 'No Alt',
        'dashicons-editor-help' => 'Help',
        'dashicons-info' => 'Info',
        'dashicons-warning' => 'Warning',
        'dashicons-editor-removeformatting' => 'Clear',
        
        // Settings & Tools
        'dashicons-admin-settings' => 'Settings',
        'dashicons-admin-generic' => 'Settings Alt',
        'dashicons-admin-tools' => 'Tools',
        'dashicons-admin-network' => 'Network',
        'dashicons-admin-plugins' => 'Plugins',
        'dashicons-admin-appearance' => 'Appearance',
        'dashicons-admin-customizer' => 'Customizer',
        'dashicons-hammer' => 'Hammer',
        'dashicons-art' => 'Art',
        'dashicons-performance' => 'Performance',
        'dashicons-universal-access' => 'Accessibility',
        'dashicons-universal-access-alt' => 'Accessibility Alt',
        
        // Social & Favorites
        'dashicons-heart' => 'Heart',
        'dashicons-star-filled' => 'Star Filled',
        'dashicons-star-empty' => 'Star Empty',
        'dashicons-star-half' => 'Star Half',
        'dashicons-thumbs-up' => 'Thumbs Up',
        'dashicons-thumbs-down' => 'Thumbs Down',
        'dashicons-flag' => 'Flag',
        'dashicons-awards' => 'Awards',
        'dashicons-facebook' => 'Facebook',
        'dashicons-facebook-alt' => 'Facebook Alt',
        'dashicons-twitter' => 'Twitter',
        'dashicons-twitter-alt' => 'Twitter Alt',
        'dashicons-instagram' => 'Instagram',
        'dashicons-youtube' => 'YouTube',
        'dashicons-linkedin' => 'LinkedIn',
        'dashicons-pinterest' => 'Pinterest',
        'dashicons-google' => 'Google',
        'dashicons-whatsapp' => 'WhatsApp',
        
        // Location & Time
        'dashicons-location' => 'Location',
        'dashicons-location-alt' => 'Location Alt',
        'dashicons-building' => 'Building',
        'dashicons-car' => 'Car',
        'dashicons-clock' => 'Clock',
        'dashicons-calendar' => 'Calendar',
        'dashicons-calendar-alt' => 'Calendar Alt',
        'dashicons-schedule' => 'Schedule',
        
        // Search & Discovery
        'dashicons-search' => 'Search',
        'dashicons-filter' => 'Filter',
        'dashicons-sort' => 'Sort',
        'dashicons-randomize' => 'Random',
        'dashicons-list-view' => 'List View',
        'dashicons-grid-view' => 'Grid View',
        'dashicons-excerpt-view' => 'Excerpt View',
        
        // Files & Documents
        'dashicons-media-document' => 'Document',
        'dashicons-media-archive' => 'Archive',
        'dashicons-media-audio' => 'Audio File',
        'dashicons-media-code' => 'Code',
        'dashicons-media-default' => 'File',
        'dashicons-media-spreadsheet' => 'Spreadsheet',
        'dashicons-media-text' => 'Text',
        'dashicons-pdf' => 'PDF',
        'dashicons-book' => 'Book',
        'dashicons-book-alt' => 'Book Alt',
        
        // Security & Privacy
        'dashicons-lock' => 'Lock',
        'dashicons-unlock' => 'Unlock',
        'dashicons-privacy' => 'Privacy',
        'dashicons-hidden' => 'Hidden',
        'dashicons-visibility' => 'Visibility',
        'dashicons-shield' => 'Shield',
        'dashicons-shield-alt' => 'Shield Alt',
        
        // System & Technical
        'dashicons-update' => 'Update',
        'dashicons-update-alt' => 'Update Alt',
        'dashicons-backup' => 'Backup',
        'dashicons-migrate' => 'Migrate',
        'dashicons-download' => 'Download',
        'dashicons-upload' => 'Upload',
        'dashicons-cloud' => 'Cloud',
        'dashicons-database' => 'Database',
        'dashicons-database-add' => 'Database Add',
        'dashicons-database-export' => 'Database Export',
        'dashicons-database-import' => 'Database Import',
        'dashicons-database-remove' => 'Database Remove',
        'dashicons-database-view' => 'Database View',
        
        // Creative & Design
        'dashicons-editor-bold' => 'Bold',
        'dashicons-editor-italic' => 'Italic',
        'dashicons-editor-ul' => 'List',
        'dashicons-editor-ol' => 'Ordered List',
        'dashicons-editor-quote' => 'Quote',
        'dashicons-editor-alignleft' => 'Align Left',
        'dashicons-editor-aligncenter' => 'Align Center',
        'dashicons-editor-alignright' => 'Align Right',
        'dashicons-editor-insertmore' => 'Insert More',
        'dashicons-editor-spellcheck' => 'Spellcheck',
        'dashicons-editor-expand' => 'Expand',
        'dashicons-editor-contract' => 'Contract',
        'dashicons-editor-kitchensink' => 'Kitchen Sink',
        'dashicons-editor-underline' => 'Underline',
        'dashicons-editor-justify' => 'Justify',
        'dashicons-editor-textcolor' => 'Text Color',
        'dashicons-editor-paste-word' => 'Paste Word',
        'dashicons-editor-paste-text' => 'Paste Text',
        'dashicons-editor-removeformatting' => 'Remove Formatting',
        'dashicons-editor-video' => 'Video Editor',
        'dashicons-editor-customchar' => 'Custom Character',
        
        // Games & Entertainment
        'dashicons-games' => 'Games',
        'dashicons-screenoptions' => 'Screen Options',
        'dashicons-info-outline' => 'Info Outline',
        'dashicons-marker' => 'Marker',
        'dashicons-palmtree' => 'Palm Tree',
        'dashicons-tickets-alt' => 'Tickets',
        'dashicons-money-alt' => 'Currency',
        'dashicons-smiley' => 'Smiley',
        'dashicons-sos' => 'SOS',
        'dashicons-superhero' => 'Superhero',
        'dashicons-superhero-alt' => 'Superhero Alt'
    );
}

/**
 * Get FontAwesome icons data
 */
function wpbnp_get_fontawesome_icons() {
    return array(
        // Navigation & Home
        'home' => 'Home',
        'house' => 'House',
        'house-user' => 'House User',
        'house-flag' => 'House Flag',
        'compass' => 'Compass',
        'location-dot' => 'Location',
        'map' => 'Map',
        'map-location-dot' => 'Map Location',
        'route' => 'Route',
        
        // Users & People
        'user' => 'User',
        'users' => 'Users',
        'user-group' => 'User Group',
        'user-friends' => 'Friends',
        'user-circle' => 'User Circle',
        'user-check' => 'User Check',
        'user-plus' => 'Add User',
        'user-minus' => 'Remove User',
        'user-edit' => 'Edit User',
        'user-cog' => 'User Settings',
        'user-shield' => 'User Shield',
        'user-secret' => 'User Secret',
        'user-tie' => 'Business User',
        'user-graduate' => 'Graduate',
        'user-astronaut' => 'Astronaut',
        'user-ninja' => 'Ninja',
        'baby' => 'Baby',
        'child' => 'Child',
        'person' => 'Person',
        'people-group' => 'People Group',
        
        // Shopping & Commerce
        'shopping-cart' => 'Shopping Cart',
        'cart-plus' => 'Add to Cart',
        'cart-arrow-down' => 'Download Cart',
        'shopping-bag' => 'Shopping Bag',
        'shopping-basket' => 'Shopping Basket',
        'store' => 'Store',
        'cash-register' => 'Cash Register',
        'credit-card' => 'Credit Card',
        'money-bill' => 'Money Bill',
        'money-bill-wave' => 'Money Wave',
        'coins' => 'Coins',
        'wallet' => 'Wallet',
        'receipt' => 'Receipt',
        'tag' => 'Tag',
        'tags' => 'Tags',
        'barcode' => 'Barcode',
        'qrcode' => 'QR Code',
        'percent' => 'Percent',
        'dollar-sign' => 'Dollar',
        'euro-sign' => 'Euro',
        'pound-sign' => 'Pound',
        'yen-sign' => 'Yen',
        'bitcoin-sign' => 'Bitcoin',
        
        // Communication & Social
        'envelope' => 'Email',
        'envelope-open' => 'Open Email',
        'inbox' => 'Inbox',
        'paper-plane' => 'Send',
        'phone' => 'Phone',
        'phone-flip' => 'Phone Flip',
        'mobile' => 'Mobile',
        'fax' => 'Fax',
        'comment' => 'Comment',
        'comments' => 'Comments',
        'message' => 'Message',
        'sms' => 'SMS',
        'whatsapp' => 'WhatsApp',
        'telegram' => 'Telegram',
        'discord' => 'Discord',
        'slack' => 'Slack',
        'skype' => 'Skype',
        'facebook' => 'Facebook',
        'twitter' => 'Twitter',
        'instagram' => 'Instagram',
        'linkedin' => 'LinkedIn',
        'youtube' => 'YouTube',
        'tiktok' => 'TikTok',
        'snapchat' => 'Snapchat',
        'pinterest' => 'Pinterest',
        'reddit' => 'Reddit',
        'tumblr' => 'Tumblr',
        'share' => 'Share',
        'share-nodes' => 'Share Network',
        'rss' => 'RSS',
        
        // Content & Media
        'image' => 'Image',
        'images' => 'Images',
        'camera' => 'Camera',
        'camera-retro' => 'Retro Camera',
        'video' => 'Video',
        'play' => 'Play',
        'pause' => 'Pause',
        'stop' => 'Stop',
        'forward' => 'Forward',
        'backward' => 'Backward',
        'step-forward' => 'Step Forward',
        'step-backward' => 'Step Backward',
        'eject' => 'Eject',
        'volume-high' => 'Volume High',
        'volume-low' => 'Volume Low',
        'volume-off' => 'Volume Off',
        'volume-mute' => 'Mute',
        'music' => 'Music',
        'headphones' => 'Headphones',
        'microphone' => 'Microphone',
        'podcast' => 'Podcast',
        'film' => 'Film',
        'photo-film' => 'Photo Film',
        'clapperboard' => 'Clapperboard',
        'tv' => 'TV',
        'display' => 'Display',
        'desktop' => 'Desktop',
        'laptop' => 'Laptop',
        'tablet' => 'Tablet',
        'mobile-screen' => 'Mobile Screen',
        
        // Navigation & Controls
        'bars' => 'Menu',
        'bars-staggered' => 'Menu Staggered',
        'ellipsis' => 'More',
        'ellipsis-vertical' => 'More Vertical',
        'arrow-up' => 'Arrow Up',
        'arrow-down' => 'Arrow Down',
        'arrow-left' => 'Arrow Left',
        'arrow-right' => 'Arrow Right',
        'arrow-up-long' => 'Long Arrow Up',
        'arrow-down-long' => 'Long Arrow Down',
        'arrow-left-long' => 'Long Arrow Left',
        'arrow-right-long' => 'Long Arrow Right',
        'chevron-up' => 'Chevron Up',
        'chevron-down' => 'Chevron Down',
        'chevron-left' => 'Chevron Left',
        'chevron-right' => 'Chevron Right',
        'angle-up' => 'Angle Up',
        'angle-down' => 'Angle Down',
        'angle-left' => 'Angle Left',
        'angle-right' => 'Angle Right',
        'caret-up' => 'Caret Up',
        'caret-down' => 'Caret Down',
        'caret-left' => 'Caret Left',
        'caret-right' => 'Caret Right',
        
        // Actions & Controls
        'plus' => 'Plus',
        'minus' => 'Minus',
        'xmark' => 'Close',
        'check' => 'Check',
        'check-circle' => 'Check Circle',
        'times-circle' => 'Times Circle',
        'exclamation' => 'Exclamation',
        'exclamation-circle' => 'Warning',
        'exclamation-triangle' => 'Warning Triangle',
        'question' => 'Question',
        'question-circle' => 'Question Circle',
        'info' => 'Info',
        'info-circle' => 'Info Circle',
        'bell' => 'Bell',
        'bell-slash' => 'Bell Off',
        'bookmark' => 'Bookmark',
        'heart' => 'Heart',
        'thumbs-up' => 'Thumbs Up',
        'thumbs-down' => 'Thumbs Down',
        'star' => 'Star',
        'flag' => 'Flag',
        'eye' => 'Eye',
        'eye-slash' => 'Eye Slash',
        'hand' => 'Hand',
        'peace' => 'Peace',
        
        // Search & Discovery
        'magnifying-glass' => 'Search',
        'filter' => 'Filter',
        'sort' => 'Sort',
        'sort-up' => 'Sort Up',
        'sort-down' => 'Sort Down',
        'sort-alpha-up' => 'Sort A-Z',
        'sort-alpha-down' => 'Sort Z-A',
        'sort-numeric-up' => 'Sort 1-9',
        'sort-numeric-down' => 'Sort 9-1',
        'list' => 'List',
        'list-ul' => 'Bullet List',
        'list-ol' => 'Numbered List',
        'th' => 'Grid',
        'th-large' => 'Large Grid',
        'th-list' => 'List View',
        'table' => 'Table',
        'border-all' => 'Table All',
        'grip-horizontal' => 'Grip Horizontal',
        'grip-vertical' => 'Grip Vertical',
        
        // Files & Documents
        'file' => 'File',
        'file-text' => 'Text File',
        'file-pdf' => 'PDF',
        'file-word' => 'Word',
        'file-excel' => 'Excel',
        'file-powerpoint' => 'PowerPoint',
        'file-image' => 'Image File',
        'file-video' => 'Video File',
        'file-audio' => 'Audio File',
        'file-archive' => 'Archive',
        'file-code' => 'Code File',
        'file-csv' => 'CSV',
        'folder' => 'Folder',
        'folder-open' => 'Open Folder',
        'folder-plus' => 'Add Folder',
        'folder-minus' => 'Remove Folder',
        'copy' => 'Copy',
        'paste' => 'Paste',
        'cut' => 'Cut',
        'scissors' => 'Scissors',
        'paperclip' => 'Attachment',
        'download' => 'Download',
        'upload' => 'Upload',
        'cloud' => 'Cloud',
        'cloud-arrow-up' => 'Cloud Upload',
        'cloud-arrow-down' => 'Cloud Download',
        
        // Settings & Tools
        'gear' => 'Settings',
        'cog' => 'Cog',
        'sliders' => 'Sliders',
        'wrench' => 'Wrench',
        'screwdriver' => 'Screwdriver',
        'hammer' => 'Hammer',
        'tools' => 'Tools',
        'toolbox' => 'Toolbox',
        'brush' => 'Brush',
        'palette' => 'Palette',
        'paint-roller' => 'Paint Roller',
        'spray-can' => 'Spray Can',
        'pen' => 'Pen',
        'pencil' => 'Pencil',
        'pen-to-square' => 'Edit',
        'marker' => 'Marker',
        'highlighter' => 'Highlighter',
        'eraser' => 'Eraser',
        'ruler' => 'Ruler',
        'compass-drafting' => 'Drafting Compass',
        
        // Security & Privacy
        'lock' => 'Lock',
        'unlock' => 'Unlock',
        'key' => 'Key',
        'shield' => 'Shield',
        'shield-halved' => 'Shield Half',
        'user-shield' => 'User Shield',
        'fingerprint' => 'Fingerprint',
        'mask' => 'Mask',
        'user-secret' => 'Secret User',
        'eye-slash' => 'Hide',
        'ban' => 'Ban',
        'circle-exclamation' => 'Alert',
        'triangle-exclamation' => 'Warning',
        'bug' => 'Bug',
        'virus' => 'Virus',
        
        // Time & Calendar
        'clock' => 'Clock',
        'stopwatch' => 'Stopwatch',
        'hourglass' => 'Hourglass',
        'calendar' => 'Calendar',
        'calendar-days' => 'Calendar Days',
        'calendar-week' => 'Calendar Week',
        'calendar-check' => 'Calendar Check',
        'calendar-plus' => 'Calendar Plus',
        'calendar-minus' => 'Calendar Minus',
        'history' => 'History',
        'rotate-left' => 'Undo',
        'rotate-right' => 'Redo',
        'clock-rotate-left' => 'History Clock',
        
        // Transportation
        'car' => 'Car',
        'taxi' => 'Taxi',
        'bus' => 'Bus',
        'truck' => 'Truck',
        'motorcycle' => 'Motorcycle',
        'bicycle' => 'Bicycle',
        'plane' => 'Plane',
        'helicopter' => 'Helicopter',
        'rocket' => 'Rocket',
        'ship' => 'Ship',
        'anchor' => 'Anchor',
        'train' => 'Train',
        'subway' => 'Subway',
        'gas-pump' => 'Gas Pump',
        'charging-station' => 'Charging Station',
        'road' => 'Road',
        'traffic-light' => 'Traffic Light',
        
        // Weather & Nature
        'sun' => 'Sun',
        'moon' => 'Moon',
        'cloud' => 'Cloud',
        'cloud-rain' => 'Rain',
        'cloud-snow' => 'Snow',
        'bolt' => 'Lightning',
        'rainbow' => 'Rainbow',
        'temperature-high' => 'Hot',
        'temperature-low' => 'Cold',
        'wind' => 'Wind',
        'tornado' => 'Tornado',
        'hurricane' => 'Hurricane',
        'tree' => 'Tree',
        'leaf' => 'Leaf',
        'seedling' => 'Seedling',
        'flower' => 'Flower',
        'mountain' => 'Mountain',
        'water' => 'Water',
        'fire' => 'Fire',
        'snowflake' => 'Snowflake',
        
        // Food & Dining
        'utensils' => 'Utensils',
        'plate-wheat' => 'Plate',
        'bowl-food' => 'Bowl',
        'cup-straw' => 'Drink',
        'mug-saucer' => 'Coffee',
        'wine-glass' => 'Wine',
        'beer-mug-empty' => 'Beer',
        'pizza-slice' => 'Pizza',
        'burger' => 'Burger',
        'hotdog' => 'Hotdog',
        'ice-cream' => 'Ice Cream',
        'candy-cane' => 'Candy',
        'apple-whole' => 'Apple',
        'carrot' => 'Carrot',
        'fish' => 'Fish',
        'drumstick-bite' => 'Chicken',
        'bread-slice' => 'Bread',
        'cheese' => 'Cheese',
        'egg' => 'Egg',
        
        // Health & Medical
        'heart-pulse' => 'Heart Rate',
        'stethoscope' => 'Stethoscope',
        'syringe' => 'Syringe',
        'pills' => 'Pills',
        'capsules' => 'Capsules',
        'bandage' => 'Bandage',
        'user-doctor' => 'Doctor',
        'user-nurse' => 'Nurse',
        'hospital' => 'Hospital',
        'ambulance' => 'Ambulance',
        'wheelchair' => 'Wheelchair',
        'crutch' => 'Crutch',
        'tooth' => 'Tooth',
        'brain' => 'Brain',
        'dna' => 'DNA',
        'virus' => 'Virus',
        'bacteria' => 'Bacteria',
        'microscope' => 'Microscope',
        
        // Sports & Activities
        'football' => 'Football',
        'basketball' => 'Basketball',
        'baseball' => 'Baseball',
        'volleyball' => 'Volleyball',
        'table-tennis-paddle-ball' => 'Ping Pong',
        'golf-ball-tee' => 'Golf',
        'bowling-ball' => 'Bowling',
        'dumbbell' => 'Dumbbell',
        'weight-hanging' => 'Weight',
        'running' => 'Running',
        'person-biking' => 'Biking',
        'person-swimming' => 'Swimming',
        'person-skiing' => 'Skiing',
        'trophy' => 'Trophy',
        'medal' => 'Medal',
        'award' => 'Award',
        'ribbon' => 'Ribbon',
        'target' => 'Target',
        'bullseye' => 'Bullseye',
        
        // Education & Learning
        'graduation-cap' => 'Graduation',
        'school' => 'School',
        'book' => 'Book',
        'book-open' => 'Open Book',
        'bookmark' => 'Bookmark',
        'pen-fancy' => 'Pen Fancy',
        'pencil-ruler' => 'Pencil Ruler',
        'calculator' => 'Calculator',
        'microscope' => 'Microscope',
        'flask' => 'Flask',
        'atom' => 'Atom',
        'dna' => 'DNA',
        'globe' => 'Globe',
        'language' => 'Language',
        'spell-check' => 'Spell Check',
        'chalkboard' => 'Chalkboard',
        'chalkboard-user' => 'Teacher',
        'apple-whole' => 'Apple',
        
        // Gaming & Entertainment
        'gamepad' => 'Gamepad',
        'chess' => 'Chess',
        'dice' => 'Dice',
        'puzzle-piece' => 'Puzzle',
        'cards-blank' => 'Cards',
        'mask' => 'Theater Mask',
        'music' => 'Music',
        'guitar' => 'Guitar',
        'drum' => 'Drum',
        'microphone' => 'Microphone',
        'headphones' => 'Headphones',
        'ticket' => 'Ticket',
        'film' => 'Film',
        'camera-movie' => 'Movie Camera',
        'popcorn' => 'Popcorn',
        'couch' => 'Couch',
        'tv' => 'TV',
        'radio' => 'Radio'
    );
}

/**
 * Get Feather icons (SVG-based)
 */
function wpbnp_get_feather_icons() {
    return array(
        'home' => 'Home',
        'menu' => 'Menu',
        'grid' => 'Grid',
        'shopping-cart' => 'Shopping Cart',
        'shopping-bag' => 'Shopping Bag',
        'user' => 'User',
        'users' => 'Users',
        'heart' => 'Heart',
        'message-circle' => 'Message',
        'phone' => 'Phone',
        'mail' => 'Email',
        'search' => 'Search',
        'camera' => 'Camera',
        'image' => 'Image',
        'video' => 'Video',
        'music' => 'Music',
        'play' => 'Play',
        'star' => 'Star',
        'bookmark' => 'Bookmark',
        'bell' => 'Bell',
        'calendar' => 'Calendar',
        'clock' => 'Clock',
        'map-pin' => 'Location',
        'settings' => 'Settings',
        'tool' => 'Tools'
    );
}

/**
 * Get Material icons
 */
function wpbnp_get_material_icons() {
    return array(
        // Navigation & Home
        'home' => 'Home',
        'house' => 'House',
        'apartment' => 'Apartment',
        'business' => 'Business',
        'location_on' => 'Location On',
        'location_off' => 'Location Off',
        'place' => 'Place',
        'map' => 'Map',
        'explore' => 'Explore',
        'navigation' => 'Navigation',
        'near_me' => 'Near Me',
        'my_location' => 'My Location',
        'compass_calibration' => 'Compass Calibration',
        'directions' => 'Directions',
        'directions_walk' => 'Walking Directions',
        'directions_run' => 'Running Directions',
        'directions_bike' => 'Bike Directions',
        'directions_car' => 'Car Directions',
        'directions_transit' => 'Transit Directions',
        'directions_boat' => 'Boat Directions',
        'flight' => 'Flight',
        'flight_takeoff' => 'Flight Takeoff',
        'flight_land' => 'Flight Land',
        
        // Users & People
        'person' => 'Person',
        'people' => 'People',
        'group' => 'Group',
        'groups' => 'Groups',
        'person_add' => 'Add Person',
        'person_remove' => 'Remove Person',
        'people_alt' => 'People Alt',
        'account_circle' => 'Account Circle',
        'account_box' => 'Account Box',
        'face' => 'Face',
        'sentiment_satisfied' => 'Satisfied',
        'sentiment_very_satisfied' => 'Very Satisfied',
        'sentiment_dissatisfied' => 'Dissatisfied',
        'sentiment_very_dissatisfied' => 'Very Dissatisfied',
        'mood' => 'Mood',
        'mood_bad' => 'Bad Mood',
        'family_restroom' => 'Family',
        'child_care' => 'Child Care',
        'elderly' => 'Elderly',
        'accessible' => 'Accessible',
        'accessibility' => 'Accessibility',
        'supervisor_account' => 'Supervisor',
        'admin_panel_settings' => 'Admin',
        'manage_accounts' => 'Manage Accounts',
        'switch_account' => 'Switch Account',
        'badge' => 'Badge',
        'card_membership' => 'Membership Card',
        'contact_mail' => 'Contact Mail',
        'contact_phone' => 'Contact Phone',
        'contacts' => 'Contacts',
        
        // Shopping & Commerce
        'shopping_cart' => 'Shopping Cart',
        'shopping_cart_checkout' => 'Cart Checkout',
        'add_shopping_cart' => 'Add to Cart',
        'remove_shopping_cart' => 'Remove from Cart',
        'shopping_bag' => 'Shopping Bag',
        'shopping_basket' => 'Shopping Basket',
        'store' => 'Store',
        'storefront' => 'Storefront',
        'local_mall' => 'Mall',
        'local_grocery_store' => 'Grocery Store',
        'local_convenience_store' => 'Convenience Store',
        'local_pharmacy' => 'Pharmacy',
        'local_gas_station' => 'Gas Station',
        'local_atm' => 'ATM',
        'payment' => 'Payment',
        'credit_card' => 'Credit Card',
        'credit_score' => 'Credit Score',
        'account_balance' => 'Account Balance',
        'account_balance_wallet' => 'Wallet',
        'attach_money' => 'Money',
        'money_off' => 'Money Off',
        'euro_symbol' => 'Euro',
        'currency_pound' => 'Pound',
        'currency_yen' => 'Yen',
        'currency_bitcoin' => 'Bitcoin',
        'savings' => 'Savings',
        'monetization_on' => 'Monetization',
        'sell' => 'Sell',
        'point_of_sale' => 'Point of Sale',
        'receipt' => 'Receipt',
        'receipt_long' => 'Long Receipt',
        'inventory' => 'Inventory',
        'warehouse' => 'Warehouse',
        'delivery_dining' => 'Delivery',
        'local_shipping' => 'Shipping',
        'track_changes' => 'Track Changes',
        'price_check' => 'Price Check',
        'price_change' => 'Price Change',
        'discount' => 'Discount',
        'percent' => 'Percent',
        'redeem' => 'Redeem',
        'card_giftcard' => 'Gift Card',
        'loyalty' => 'Loyalty',
        'shopping_cart_checkout' => 'Checkout',
        
        // Communication & Social
        'mail' => 'Mail',
        'email' => 'Email',
        'inbox' => 'Inbox',
        'outbox' => 'Outbox',
        'send' => 'Send',
        'forward_to_inbox' => 'Forward',
        'reply' => 'Reply',
        'reply_all' => 'Reply All',
        'mark_email_read' => 'Mark Read',
        'mark_email_unread' => 'Mark Unread',
        'drafts' => 'Drafts',
        'archive' => 'Archive',
        'unarchive' => 'Unarchive',
        'delete_forever' => 'Delete Forever',
        'phone' => 'Phone',
        'call' => 'Call',
        'call_end' => 'End Call',
        'call_made' => 'Call Made',
        'call_received' => 'Call Received',
        'call_missed' => 'Call Missed',
        'phone_in_talk' => 'Phone in Talk',
        'phone_callback' => 'Phone Callback',
        'phone_forwarded' => 'Phone Forwarded',
        'phone_locked' => 'Phone Locked',
        'phone_paused' => 'Phone Paused',
        'smartphone' => 'Smartphone',
        'tablet' => 'Tablet',
        'laptop' => 'Laptop',
        'desktop_windows' => 'Desktop',
        'computer' => 'Computer',
        'devices' => 'Devices',
        'chat' => 'Chat',
        'chat_bubble' => 'Chat Bubble',
        'chat_bubble_outline' => 'Chat Outline',
        'message' => 'Message',
        'sms' => 'SMS',
        'textsms' => 'Text SMS',
        'question_answer' => 'Q&A',
        'forum' => 'Forum',
        'comment' => 'Comment',
        'speaker_notes' => 'Speaker Notes',
        'record_voice_over' => 'Voice Over',
        'campaign' => 'Campaign',
        'announcement' => 'Announcement',
        'notifications' => 'Notifications',
        'notifications_active' => 'Notifications Active',
        'notifications_off' => 'Notifications Off',
        'notifications_none' => 'No Notifications',
        'notifications_paused' => 'Notifications Paused',
        'share' => 'Share',
        'ios_share' => 'iOS Share',
        'screen_share' => 'Screen Share',
        'rss_feed' => 'RSS Feed',
        'public' => 'Public',
        'language' => 'Language',
        'translate' => 'Translate',
        
        // Content & Media
        'image' => 'Image',
        'photo' => 'Photo',
        'photo_library' => 'Photo Library',
        'photo_album' => 'Photo Album',
        'collections' => 'Collections',
        'burst_mode' => 'Burst Mode',
        'camera' => 'Camera',
        'camera_alt' => 'Camera Alt',
        'camera_front' => 'Front Camera',
        'camera_rear' => 'Rear Camera',
        'camera_roll' => 'Camera Roll',
        'switch_camera' => 'Switch Camera',
        'add_a_photo' => 'Add Photo',
        'photo_camera' => 'Photo Camera',
        'videocam' => 'Video Camera',
        'videocam_off' => 'Video Off',
        'video_library' => 'Video Library',
        'video_call' => 'Video Call',
        'video_settings' => 'Video Settings',
        'movie' => 'Movie',
        'movie_creation' => 'Movie Creation',
        'theaters' => 'Theaters',
        'local_movies' => 'Local Movies',
        'play_arrow' => 'Play',
        'play_circle' => 'Play Circle',
        'play_circle_filled' => 'Play Filled',
        'play_circle_outline' => 'Play Outline',
        'pause' => 'Pause',
        'pause_circle' => 'Pause Circle',
        'pause_circle_filled' => 'Pause Filled',
        'pause_circle_outline' => 'Pause Outline',
        'stop' => 'Stop',
        'stop_circle' => 'Stop Circle',
        'fast_forward' => 'Fast Forward',
        'fast_rewind' => 'Fast Rewind',
        'skip_next' => 'Skip Next',
        'skip_previous' => 'Skip Previous',
        'replay' => 'Replay',
        'replay_10' => 'Replay 10',
        'replay_30' => 'Replay 30',
        'forward_10' => 'Forward 10',
        'forward_30' => 'Forward 30',
        'shuffle' => 'Shuffle',
        'repeat' => 'Repeat',
        'repeat_one' => 'Repeat One',
        'volume_up' => 'Volume Up',
        'volume_down' => 'Volume Down',
        'volume_mute' => 'Volume Mute',
        'volume_off' => 'Volume Off',
        'music_note' => 'Music Note',
        'library_music' => 'Music Library',
        'queue_music' => 'Music Queue',
        'playlist_add' => 'Add to Playlist',
        'playlist_add_check' => 'Playlist Added',
        'playlist_play' => 'Play Playlist',
        'album' => 'Album',
        'artist' => 'Artist',
        'equalizer' => 'Equalizer',
        'graphic_eq' => 'Graphic EQ',
        'mic' => 'Microphone',
        'mic_off' => 'Mic Off',
        'mic_none' => 'Mic None',
        'mic_external_on' => 'External Mic',
        'headset' => 'Headset',
        'headset_mic' => 'Headset Mic',
        'headset_off' => 'Headset Off',
        'hearing' => 'Hearing',
        'surround_sound' => 'Surround Sound',
        'audiotrack' => 'Audio Track',
        'radio' => 'Radio',
        'podcasts' => 'Podcasts',
        'library_add' => 'Add to Library',
        'library_books' => 'Library Books',
        'tv' => 'TV',
        'tv_off' => 'TV Off',
        'live_tv' => 'Live TV',
        'ondemand_video' => 'On Demand Video',
        'video_collection' => 'Video Collection',
        'closed_caption' => 'Closed Caption',
        'closed_caption_disabled' => 'Captions Off',
        'subtitles' => 'Subtitles',
        'subtitles_off' => 'Subtitles Off',
        'cast' => 'Cast',
        'cast_connected' => 'Cast Connected',
        'airplay' => 'AirPlay',
        'screen_rotation' => 'Screen Rotation',
        'stay_current_landscape' => 'Landscape',
        'stay_current_portrait' => 'Portrait',
        'crop' => 'Crop',
        'crop_original' => 'Crop Original',
        'crop_free' => 'Crop Free',
        'crop_landscape' => 'Crop Landscape',
        'crop_portrait' => 'Crop Portrait',
        'crop_square' => 'Crop Square',
        'rotate_90_degrees_ccw' => 'Rotate CCW',
        'rotate_left' => 'Rotate Left',
        'rotate_right' => 'Rotate Right',
        'flip' => 'Flip',
        'transform' => 'Transform',
        'tune' => 'Tune',
        'auto_fix_high' => 'Auto Fix High',
        'auto_fix_normal' => 'Auto Fix Normal',
        'auto_fix_off' => 'Auto Fix Off',
        'auto_awesome' => 'Auto Awesome',
        'photo_filter' => 'Photo Filter',
        'filter' => 'Filter',
        'filter_b_and_w' => 'B&W Filter',
        'filter_vintage' => 'Vintage Filter',
        'filter_drama' => 'Drama Filter',
        'filter_hdr' => 'HDR Filter',
        'filter_none' => 'No Filter',
        'palette' => 'Palette',
        'colorize' => 'Colorize',
        'color_lens' => 'Color Lens',
        'gradient' => 'Gradient',
        'brush' => 'Brush',
        'format_paint' => 'Format Paint',
        'gesture' => 'Gesture',
        'create' => 'Create',
        'edit' => 'Edit',
        'content_cut' => 'Cut',
        'content_copy' => 'Copy',
        'content_paste' => 'Paste',
        'undo' => 'Undo',
        'redo' => 'Redo',
        
        // Navigation & Controls
        'menu' => 'Menu',
        'menu_open' => 'Menu Open',
        'more_horiz' => 'More Horizontal',
        'more_vert' => 'More Vertical',
        'apps' => 'Apps',
        'app_registration' => 'App Registration',
        'dashboard' => 'Dashboard',
        'dashboard_customize' => 'Customize Dashboard',
        'widgets' => 'Widgets',
        'view_list' => 'List View',
        'view_module' => 'Module View',
        'view_quilt' => 'Quilt View',
        'view_stream' => 'Stream View',
        'view_agenda' => 'Agenda View',
        'view_array' => 'Array View',
        'view_carousel' => 'Carousel View',
        'view_column' => 'Column View',
        'view_compact' => 'Compact View',
        'view_comfortable' => 'Comfortable View',
        'view_comfy' => 'Comfy View',
        'view_headline' => 'Headline View',
        'view_sidebar' => 'Sidebar View',
        'view_week' => 'Week View',
        'table_chart' => 'Table Chart',
        'table_rows' => 'Table Rows',
        'reorder' => 'Reorder',
        'drag_handle' => 'Drag Handle',
        'drag_indicator' => 'Drag Indicator',
        'format_list_bulleted' => 'Bulleted List',
        'format_list_numbered' => 'Numbered List',
        'format_indent_increase' => 'Increase Indent',
        'format_indent_decrease' => 'Decrease Indent',
        'format_align_left' => 'Align Left',
        'format_align_center' => 'Align Center',
        'format_align_right' => 'Align Right',
        'format_align_justify' => 'Justify',
        'format_bold' => 'Bold',
        'format_italic' => 'Italic',
        'format_underlined' => 'Underline',
        'format_strikethrough' => 'Strikethrough',
        'format_clear' => 'Clear Format',
        'format_color_text' => 'Text Color',
        'format_color_fill' => 'Fill Color',
        'format_color_reset' => 'Reset Color',
        'format_size' => 'Font Size',
        'text_fields' => 'Text Fields',
        'title' => 'Title',
        'subject' => 'Subject',
        'short_text' => 'Short Text',
        'notes' => 'Notes',
        'article' => 'Article',
        'wrap_text' => 'Wrap Text',
        'vertical_align_top' => 'Align Top',
        'vertical_align_center' => 'Align Center',
        'vertical_align_bottom' => 'Align Bottom',
        'arrow_upward' => 'Arrow Up',
        'arrow_downward' => 'Arrow Down',
        'arrow_back' => 'Arrow Back',
        'arrow_forward' => 'Arrow Forward',
        'arrow_back_ios' => 'Back iOS',
        'arrow_forward_ios' => 'Forward iOS',
        'keyboard_arrow_up' => 'Keyboard Up',
        'keyboard_arrow_down' => 'Keyboard Down',
        'keyboard_arrow_left' => 'Keyboard Left',
        'keyboard_arrow_right' => 'Keyboard Right',
        'expand_less' => 'Expand Less',
        'expand_more' => 'Expand More',
        'chevron_left' => 'Chevron Left',
        'chevron_right' => 'Chevron Right',
        'first_page' => 'First Page',
        'last_page' => 'Last Page',
        'unfold_less' => 'Unfold Less',
        'unfold_more' => 'Unfold More',
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit Fullscreen',
        'open_in_full' => 'Open in Full',
        'close_fullscreen' => 'Close Fullscreen',
        'fit_screen' => 'Fit Screen',
        'zoom_in' => 'Zoom In',
        'zoom_out' => 'Zoom Out',
        'zoom_out_map' => 'Zoom Out Map',
        'center_focus_strong' => 'Center Focus',
        'center_focus_weak' => 'Center Focus Weak',
        'tab' => 'Tab',
        'tab_unselected' => 'Tab Unselected',
        'keyboard_tab' => 'Keyboard Tab',
        'keyboard_return' => 'Return',
        'keyboard_backspace' => 'Backspace',
        'keyboard_capslock' => 'Caps Lock',
        'space_bar' => 'Space Bar',
        
        // Actions & Controls
        'add' => 'Add',
        'add_circle' => 'Add Circle',
        'add_circle_outline' => 'Add Circle Outline',
        'add_box' => 'Add Box',
        'remove' => 'Remove',
        'remove_circle' => 'Remove Circle',
        'remove_circle_outline' => 'Remove Circle Outline',
        'clear' => 'Clear',
        'close' => 'Close',
        'cancel' => 'Cancel',
        'block' => 'Block',
        'do_not_disturb' => 'Do Not Disturb',
        'do_not_disturb_alt' => 'Do Not Disturb Alt',
        'check' => 'Check',
        'check_circle' => 'Check Circle',
        'check_circle_outline' => 'Check Circle Outline',
        'check_box' => 'Check Box',
        'check_box_outline_blank' => 'Check Box Blank',
        'radio_button_checked' => 'Radio Checked',
        'radio_button_unchecked' => 'Radio Unchecked',
        'toggle_on' => 'Toggle On',
        'toggle_off' => 'Toggle Off',
        'done' => 'Done',
        'done_all' => 'Done All',
        'done_outline' => 'Done Outline',
        'select_all' => 'Select All',
        'deselect' => 'Deselect',
        'indeterminate_check_box' => 'Indeterminate',
        'help' => 'Help',
        'help_outline' => 'Help Outline',
        'help_center' => 'Help Center',
        'contact_support' => 'Contact Support',
        'live_help' => 'Live Help',
        'info' => 'Info',
        'info_outline' => 'Info Outline',
        'error' => 'Error',
        'error_outline' => 'Error Outline',
        'warning' => 'Warning',
        'warning_amber' => 'Warning Amber',
        'report' => 'Report',
        'report_problem' => 'Report Problem',
        'report_off' => 'Report Off',
        'dangerous' => 'Dangerous',
        'verified' => 'Verified',
        'verified_user' => 'Verified User',
        'security' => 'Security',
        'gpp_good' => 'Good',
        'gpp_bad' => 'Bad',
        'gpp_maybe' => 'Maybe',
        'priority_high' => 'High Priority',
        'flag' => 'Flag',
        'flag_circle' => 'Flag Circle',
        'outlined_flag' => 'Outlined Flag',
        'assistant' => 'Assistant',
        'assistant_photo' => 'Assistant Photo',
        'recommend' => 'Recommend',
        'thumb_up' => 'Thumb Up',
        'thumb_down' => 'Thumb Down',
        'thumb_up_alt' => 'Thumb Up Alt',
        'thumb_down_alt' => 'Thumb Down Alt',
        'thumbs_up_down' => 'Thumbs Up Down',
        
        // Social & Favorites
        'favorite' => 'Favorite',
        'favorite_border' => 'Favorite Border',
        'favorite_outline' => 'Favorite Outline',
        'star' => 'Star',
        'star_border' => 'Star Border',
        'star_outline' => 'Star Outline',
        'star_half' => 'Star Half',
        'star_purple500' => 'Purple Star',
        'star_rate' => 'Star Rate',
        'grade' => 'Grade',
        'bookmark' => 'Bookmark',
        'bookmark_border' => 'Bookmark Border',
        'bookmark_outline' => 'Bookmark Outline',
        'bookmark_add' => 'Bookmark Add',
        'bookmark_added' => 'Bookmark Added',
        'bookmark_remove' => 'Bookmark Remove',
        'bookmarks' => 'Bookmarks',
        'turned_in' => 'Turned In',
        'turned_in_not' => 'Not Turned In',
        'label' => 'Label',
        'label_important' => 'Important Label',
        'label_important_outline' => 'Important Outline',
        'label_outline' => 'Label Outline',
        'label_off' => 'Label Off',
        'new_label' => 'New Label',
        'loyalty' => 'Loyalty',
        'card_membership' => 'Membership',
        'volunteer_activism' => 'Volunteer',
        'emoji_emotions' => 'Emotions',
        'emoji_events' => 'Events',
        'emoji_flags' => 'Flags',
        'emoji_food_beverage' => 'Food Beverage',
        'emoji_nature' => 'Nature',
        'emoji_objects' => 'Objects',
        'emoji_people' => 'People',
        'emoji_symbols' => 'Symbols',
        'emoji_transportation' => 'Transportation',
        'celebration' => 'Celebration',
        'party_mode' => 'Party Mode',
        'cake' => 'Cake',
        'local_florist' => 'Florist',
        'attractions' => 'Attractions',
        'festival' => 'Festival',
        'sports' => 'Sports',
        'sports_esports' => 'Esports',
        'sports_handball' => 'Handball',
        'sports_basketball' => 'Basketball',
        'sports_football' => 'Football',
        'sports_soccer' => 'Soccer',
        'sports_tennis' => 'Tennis',
        'sports_golf' => 'Golf',
        'sports_baseball' => 'Baseball',
        'sports_volleyball' => 'Volleyball',
        'sports_hockey' => 'Hockey',
        'sports_cricket' => 'Cricket',
        'sports_rugby' => 'Rugby',
        'pool' => 'Pool',
        'fitness_center' => 'Fitness Center',
        'self_improvement' => 'Self Improvement',
        'spa' => 'Spa',
        'hot_tub' => 'Hot Tub',
        
        // Search & Discovery
        'search' => 'Search',
        'search_off' => 'Search Off',
        'youtube_searched_for' => 'YouTube Search',
        'manage_search' => 'Manage Search',
        'filter_list' => 'Filter List',
        'filter_list_alt' => 'Filter List Alt',
        'filter_alt' => 'Filter Alt',
        'sort' => 'Sort',
        'sort_by_alpha' => 'Sort Alpha',
        'import_export' => 'Import Export',
        'swap_vert' => 'Swap Vertical',
        'swap_horiz' => 'Swap Horizontal',
        'low_priority' => 'Low Priority',
        'trending_up' => 'Trending Up',
        'trending_down' => 'Trending Down',
        'trending_flat' => 'Trending Flat',
        'timeline' => 'Timeline',
        'analytics' => 'Analytics',
        'insights' => 'Insights',
        'query_stats' => 'Query Stats',
        'assessment' => 'Assessment',
        'poll' => 'Poll',
        'quiz' => 'Quiz',
        'grading' => 'Grading',
        'visibility' => 'Visibility',
        'visibility_off' => 'Visibility Off',
        'preview' => 'Preview',
        'pageview' => 'Page View',
        'find_in_page' => 'Find in Page',
        'find_replace' => 'Find Replace',
        'saved_search' => 'Saved Search',
        'history' => 'History',
        'history_toggle_off' => 'History Off',
        'restore' => 'Restore',
        'restore_from_trash' => 'Restore from Trash',
        'restore_page' => 'Restore Page',
        'compare' => 'Compare',
        'compare_arrows' => 'Compare Arrows',
        'difference' => 'Difference',
        'screen_search_desktop' => 'Desktop Search',
        'track_changes' => 'Track Changes',
        'change_history' => 'Change History',
        'update' => 'Update',
        'refresh' => 'Refresh',
        'cached' => 'Cached',
        'offline_bolt' => 'Offline',
        'sync' => 'Sync',
        'sync_alt' => 'Sync Alt',
        'sync_disabled' => 'Sync Disabled',
        'sync_problem' => 'Sync Problem',
        'autorenew' => 'Auto Renew',
        'loop' => 'Loop',
        
        // Files & Documents
        'folder' => 'Folder',
        'folder_open' => 'Folder Open',
        'folder_shared' => 'Folder Shared',
        'folder_special' => 'Folder Special',
        'create_new_folder' => 'New Folder',
        'snippet_folder' => 'Snippet Folder',
        'rule_folder' => 'Rule Folder',
        'topic' => 'Topic',
        'insert_drive_file' => 'Insert File',
        'description' => 'Description',
        'article' => 'Article',
        'text_snippet' => 'Text Snippet',
        'note' => 'Note',
        'note_add' => 'Add Note',
        'note_alt' => 'Note Alt',
        'sticky_note_2' => 'Sticky Note',
        'post_add' => 'Add Post',
        'dynamic_feed' => 'Dynamic Feed',
        'feed' => 'Feed',
        'rss_feed' => 'RSS Feed',
        'list_alt' => 'List Alt',
        'assignment' => 'Assignment',
        'assignment_turned_in' => 'Assignment Turned In',
        'assignment_late' => 'Assignment Late',
        'assignment_return' => 'Assignment Return',
        'assignment_returned' => 'Assignment Returned',
        'assignment_ind' => 'Assignment Individual',
        'task' => 'Task',
        'task_alt' => 'Task Alt',
        'checklist' => 'Checklist',
        'checklist_rtl' => 'Checklist RTL',
        'fact_check' => 'Fact Check',
        'plagiarism' => 'Plagiarism',
        'source' => 'Source',
        'content_copy' => 'Copy',
        'content_cut' => 'Cut',
        'content_paste' => 'Paste',
        'content_paste_off' => 'Paste Off',
        'content_paste_go' => 'Paste Go',
        'content_paste_search' => 'Paste Search',
        'link' => 'Link',
        'link_off' => 'Link Off',
        'attachment' => 'Attachment',
        'attach_file' => 'Attach File',
        'attach_email' => 'Attach Email',
        'download' => 'Download',
        'download_done' => 'Download Done',
        'download_for_offline' => 'Download Offline',
        'downloading' => 'Downloading',
        'upload' => 'Upload',
        'upload_file' => 'Upload File',
        'drive_folder_upload' => 'Upload Folder',
        'cloud' => 'Cloud',
        'cloud_upload' => 'Cloud Upload',
        'cloud_download' => 'Cloud Download',
        'cloud_done' => 'Cloud Done',
        'cloud_off' => 'Cloud Off',
        'cloud_sync' => 'Cloud Sync',
        'cloud_circle' => 'Cloud Circle',
        'cloud_queue' => 'Cloud Queue',
        'backup' => 'Backup',
        'backup_table' => 'Backup Table',
        'restore' => 'Restore',
        'save' => 'Save',
        'save_alt' => 'Save Alt',
        'save_as' => 'Save As',
        'unarchive' => 'Unarchive',
        'inventory' => 'Inventory',
        'inventory_2' => 'Inventory 2',
        'file_copy' => 'File Copy',
        'file_present' => 'File Present',
        'file_download' => 'File Download',
        'file_download_done' => 'File Download Done',
        'file_download_off' => 'File Download Off',
        'file_upload' => 'File Upload',
        'folder_copy' => 'Folder Copy',
        'folder_delete' => 'Folder Delete',
        'folder_zip' => 'Folder Zip',
        'compress' => 'Compress',
        'storage' => 'Storage',
        'sd_storage' => 'SD Storage',
        'usb' => 'USB',
        'sim_card' => 'SIM Card',
        'sd_card' => 'SD Card',
        'memory' => 'Memory',
        'computer' => 'Computer',
        'laptop_chromebook' => 'Chromebook',
        'laptop_mac' => 'MacBook',
        'laptop_windows' => 'Windows Laptop',
        'tablet_mac' => 'iPad',
        'tablet_android' => 'Android Tablet',
        'phone_iphone' => 'iPhone',
        'phone_android' => 'Android Phone',
        'watch' => 'Watch',
        'speaker' => 'Speaker',
        'speaker_group' => 'Speaker Group',
        'headset' => 'Headset',
        'keyboard' => 'Keyboard',
        'mouse' => 'Mouse',
        'scanner' => 'Scanner',
        'print' => 'Print',
        'local_printshop' => 'Print Shop',
        
        // Settings & Tools
        'settings' => 'Settings',
        'settings_applications' => 'App Settings',
        'settings_backup_restore' => 'Backup Settings',
        'settings_bluetooth' => 'Bluetooth Settings',
        'settings_brightness' => 'Brightness Settings',
        'settings_cell' => 'Cell Settings',
        'settings_ethernet' => 'Ethernet Settings',
        'settings_input_antenna' => 'Antenna Settings',
        'settings_input_component' => 'Component Settings',
        'settings_input_composite' => 'Composite Settings',
        'settings_input_hdmi' => 'HDMI Settings',
        'settings_input_svideo' => 'S-Video Settings',
        'settings_overscan' => 'Overscan Settings',
        'settings_phone' => 'Phone Settings',
        'settings_power' => 'Power Settings',
        'settings_remote' => 'Remote Settings',
        'settings_suggest' => 'Suggest Settings',
        'settings_system_daydream' => 'Daydream Settings',
        'settings_voice' => 'Voice Settings',
        'build' => 'Build',
        'build_circle' => 'Build Circle',
        'construction' => 'Construction',
        'engineering' => 'Engineering',
        'handyman' => 'Handyman',
        'home_repair_service' => 'Home Repair',
        'plumbing' => 'Plumbing',
        'electrical_services' => 'Electrical',
        'miscellaneous_services' => 'Miscellaneous',
        'design_services' => 'Design Services',
        'architecture' => 'Architecture',
        'carpenter' => 'Carpenter',
        'cleaning_services' => 'Cleaning',
        'pest_control' => 'Pest Control',
        'roofing' => 'Roofing',
        'hvac' => 'HVAC',
        'yard_work' => 'Yard Work',
        'landscape' => 'Landscape',
        'agriculture' => 'Agriculture',
        'precision_manufacturing' => 'Manufacturing',
        'factory' => 'Factory',
        'inventory_2' => 'Inventory',
        'science' => 'Science',
        'biotech' => 'Biotech',
        'psychology' => 'Psychology',
        'psychology_alt' => 'Psychology Alt',
        'emoji_objects' => 'Objects',
        'lightbulb' => 'Lightbulb',
        'lightbulb_outline' => 'Lightbulb Outline',
        'wb_incandescent' => 'Incandescent',
        'tips_and_updates' => 'Tips',
        'auto_fix_high' => 'Auto Fix High',
        'auto_fix_normal' => 'Auto Fix Normal',
        'auto_fix_off' => 'Auto Fix Off',
        'tune' => 'Tune',
        'build' => 'Build',
        'developer_mode' => 'Developer Mode',
        'code' => 'Code',
        'terminal' => 'Terminal',
        'integration_instructions' => 'Integration',
        'api' => 'API',
        'webhook' => 'Webhook',
        'schema' => 'Schema',
        'data_object' => 'Data Object',
        'functions' => 'Functions',
        'javascript' => 'JavaScript',
        'css' => 'CSS',
        'html' => 'HTML',
        'extension' => 'Extension',
        'plugin' => 'Plugin',
        'widgets' => 'Widgets',
        'dashboard' => 'Dashboard',
        'admin_panel_settings' => 'Admin Panel',
        'control_panel' => 'Control Panel',
        'tune' => 'Tune',
        'equalizer' => 'Equalizer',
        'graphic_eq' => 'Graphic EQ',
        'linear_scale' => 'Linear Scale',
        'multiline_chart' => 'Multiline Chart',
        'show_chart' => 'Show Chart',
        'trending_up' => 'Trending Up',
        'trending_down' => 'Trending Down',
        'trending_flat' => 'Trending Flat',
        'leaderboard' => 'Leaderboard',
        'speed' => 'Speed',
        'shutter_speed' => 'Shutter Speed',
        'timer' => 'Timer',
        'timer_off' => 'Timer Off',
        'timer_3' => 'Timer 3',
        'timer_10' => 'Timer 10',
        'timelapse' => 'Timelapse',
        'slow_motion_video' => 'Slow Motion',
        'av_timer' => 'AV Timer',
        
        // Security & Privacy
        'lock' => 'Lock',
        'lock_open' => 'Lock Open',
        'lock_outline' => 'Lock Outline',
        'lock_clock' => 'Lock Clock',
        'vpn_lock' => 'VPN Lock',
        'enhanced_encryption' => 'Enhanced Encryption',
        'no_encryption' => 'No Encryption',
        'gpp_good' => 'Good',
        'gpp_bad' => 'Bad',
        'gpp_maybe' => 'Maybe',
        'verified' => 'Verified',
        'verified_user' => 'Verified User',
        'admin_panel_settings' => 'Admin',
        'supervisor_account' => 'Supervisor',
        'manage_accounts' => 'Manage Accounts',
        'shield' => 'Shield',
        'policy' => 'Policy',
        'privacy_tip' => 'Privacy Tip',
        'security' => 'Security',
        'fingerprint' => 'Fingerprint',
        'key' => 'Key',
        'key_off' => 'Key Off',
        'password' => 'Password',
        'pin' => 'PIN',
        'pattern' => 'Pattern',
        'face' => 'Face',
        'face_unlock' => 'Face Unlock',
        'remove_moderator' => 'Remove Moderator',
        'person_off' => 'Person Off',
        'person_remove' => 'Person Remove',
        'block' => 'Block',
        'visibility' => 'Visibility',
        'visibility_off' => 'Visibility Off',
        'remove_red_eye' => 'Remove Red Eye',
        'https' => 'HTTPS',
        'http' => 'HTTP',
        'vpn_key' => 'VPN Key',
        'vpn_key_off' => 'VPN Key Off',
        'wifi_protected_setup' => 'WiFi Protected',
        'network_locked' => 'Network Locked',
        'network_check' => 'Network Check',
        'power_off' => 'Power Off',
        'power_settings_new' => 'Power Settings',
        'logout' => 'Logout',
        'login' => 'Login',
        'app_blocking' => 'App Blocking',
        'disabled_by_default' => 'Disabled',
        'do_not_disturb' => 'Do Not Disturb',
        'do_not_disturb_alt' => 'Do Not Disturb Alt',
        'do_not_disturb_off' => 'Do Not Disturb Off',
        'do_not_disturb_on' => 'Do Not Disturb On',
        'phonelink_erase' => 'Phonelink Erase',
        'phonelink_lock' => 'Phonelink Lock',
        'screen_lock_landscape' => 'Screen Lock Landscape',
        'screen_lock_portrait' => 'Screen Lock Portrait',
        'screen_lock_rotation' => 'Screen Lock Rotation',
        'security_update' => 'Security Update',
        'security_update_good' => 'Security Update Good',
        'security_update_warning' => 'Security Update Warning',
        'gavel' => 'Gavel',
        'balance' => 'Balance',
        'account_balance' => 'Account Balance',
        'copyright' => 'Copyright',
        'policy' => 'Policy',
        
        // Time & Calendar
        'access_time' => 'Access Time',
        'access_time_filled' => 'Access Time Filled',
        'schedule' => 'Schedule',
        'today' => 'Today',
        'date_range' => 'Date Range',
        'event' => 'Event',
        'event_available' => 'Event Available',
        'event_busy' => 'Event Busy',
        'event_note' => 'Event Note',
        'event_seat' => 'Event Seat',
        'calendar_today' => 'Calendar Today',
        'calendar_month' => 'Calendar Month',
        'calendar_view_day' => 'Calendar Day',
        'calendar_view_week' => 'Calendar Week',
        'calendar_view_month' => 'Calendar Month View',
        'perm_contact_calendar' => 'Contact Calendar',
        'watch_later' => 'Watch Later',
        'query_builder' => 'Query Builder',
        'alarm' => 'Alarm',
        'alarm_add' => 'Add Alarm',
        'alarm_off' => 'Alarm Off',
        'alarm_on' => 'Alarm On',
        'snooze' => 'Snooze',
        'timer' => 'Timer',
        'timer_off' => 'Timer Off',
        'hourglass_empty' => 'Hourglass Empty',
        'hourglass_full' => 'Hourglass Full',
        'hourglass_top' => 'Hourglass Top',
        'hourglass_bottom' => 'Hourglass Bottom',
        'more_time' => 'More Time',
        'pending' => 'Pending',
        'pending_actions' => 'Pending Actions',
        'schedule_send' => 'Schedule Send',
        'upcoming' => 'Upcoming',
        'update' => 'Update',
        'history' => 'History',
        'access_alarms' => 'Access Alarms',
        'timelapse' => 'Timelapse',
        'time_to_leave' => 'Time to Leave',
        'av_timer' => 'AV Timer',
        'free_breakfast' => 'Free Breakfast',
        'schedule' => 'Schedule',
        'date_range' => 'Date Range',
        'event_repeat' => 'Event Repeat',
        'repeat' => 'Repeat',
        'repeat_one' => 'Repeat One',
        'repeat_on' => 'Repeat On',
        'repeat_one_on' => 'Repeat One On',
        'workspaces' => 'Workspaces',
        'weekend' => 'Weekend',
        'work' => 'Work',
        'work_off' => 'Work Off',
        'work_outline' => 'Work Outline',
        'business_center' => 'Business Center',
        'free_cancellation' => 'Free Cancellation',
        'cancel_presentation' => 'Cancel Presentation',
        'cancel_schedule_send' => 'Cancel Schedule',
        'next_week' => 'Next Week',
        'next_plan' => 'Next Plan',
        'today' => 'Today',
        'tomorrow' => 'Tomorrow',
        'date_range' => 'Date Range',
        'date_range_outlined' => 'Date Range Outlined',
        'start' => 'Start',
        'not_started' => 'Not Started',
        'pause_presentation' => 'Pause Presentation',
        'play_lesson' => 'Play Lesson',
        'skip_next' => 'Skip Next',
        'skip_previous' => 'Skip Previous'
    );
}

/**
 * Get Bootstrap Icons data
 */
function wpbnp_get_bootstrap_icons() {
    return array(
        'house' => 'House',
        'house-door' => 'House Door',
        'cart' => 'Cart',
        'cart-fill' => 'Cart Fill',
        'person' => 'Person',
        'person-fill' => 'Person Fill',
        'heart' => 'Heart',
        'heart-fill' => 'Heart Fill',
        'star' => 'Star',
        'star-fill' => 'Star Fill',
        'search' => 'Search',
        'gear' => 'Gear',
        'gear-fill' => 'Gear Fill',
        'list' => 'List',
        'grid' => 'Grid',
        'phone' => 'Phone',
        'envelope' => 'Envelope',
        'calendar' => 'Calendar',
        'clock' => 'Clock',
        'camera' => 'Camera',
        'image' => 'Image',
        'music-note' => 'Music Note',
        'play' => 'Play',
        'pause' => 'Pause'
    );
}

/**
 * Get Apple SF Symbols (iOS) icons data
 */
function wpbnp_get_apple_icons() {
    return array(
        'house' => 'House',
        'house-fill' => 'House Fill',
        'cart' => 'Cart',
        'cart-fill' => 'Cart Fill',
        'person' => 'Person',
        'person-fill' => 'Person Fill',
        'heart' => 'Heart',
        'heart-fill' => 'Heart Fill',
        'message' => 'Message',
        'phone' => 'Phone',
        'envelope' => 'Mail',
        'magnifyingglass' => 'Search',
        'camera' => 'Camera',
        'gearshape' => 'Settings',
        'star' => 'Star',
        'star-fill' => 'Star Fill',
        'list-bullet' => 'Menu',
        'square-grid-2x2' => 'Grid'
    );
}

/**
 * Get icons for a specific preset
 */
function wpbnp_get_preset_icons($preset) {
    $icon_sets = array(
        'minimal' => wpbnp_get_dashicons(),
        'dark' => wpbnp_get_dashicons(),
        'material' => wpbnp_get_material_icons(),
        'ios' => wpbnp_get_apple_icons(),
        'glassmorphism' => wpbnp_get_apple_icons(),
        'neumorphism' => wpbnp_get_apple_icons(),
        'cyberpunk' => wpbnp_get_material_icons(),
        'vintage' => wpbnp_get_dashicons(),
        'gradient' => wpbnp_get_apple_icons(),
        'floating' => wpbnp_get_apple_icons()
    );
    
    return isset($icon_sets[$preset]) ? $icon_sets[$preset] : wpbnp_get_dashicons();
}

/**
 * Get cart count (WooCommerce integration)
 */
function wpbnp_get_cart_count() {
    if (function_exists('WC') && WC()->cart) {
        return WC()->cart->get_cart_contents_count();
    }
    return 0;
}

/**
 * Get badge count for specific item
 */
function wpbnp_get_badge_count($item_id) {
    switch ($item_id) {
        case 'cart':
            return wpbnp_get_cart_count();
        case 'notifications':
            // Add your notification count logic here
            return 0;
        default:
            return 0;
    }
}
